package tech.androidplay.sonali.todo.network.model

data class Customer(
    val DLVerified: Int,
    val DLback: String,
    val DLfront: String,
    val DLnumber: String,
    val DLnumberVerified: Int,
    val IDVerified: Int,
    val IDtype: String,
    val address: String,
    val alternateNo: Any,
    val city: String,
    val createdAt: String,
    val createdBy: Any,
    val email: String,
    val emailVerified: Int,
    val fName: String,
    val id: Int,
    val idProof: String,
    val idProofBack: String,
    val lName: String,
    val mobile: String,
    val mobileVerified: Int,
    val otherDetails: Any,
    val otherProof: Any,
    val penaltyCharge: Int,
    val pinCode: Int,
    val profilePicture: Any,
    val referalCode: String,
    val signUpType: String,
    val socialLoginId: Any,
    val socialLoginType: Any,
    val state: String,
    val status: Int,
    val updatedAt: String
)